package com.smartresponse.service;
import com.smartresponse.api.*; import com.smartresponse.domain.*; import com.smartresponse.repository.*; import jakarta.mail.internet.MimeMessage; import org.springframework.beans.factory.annotation.Value; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.core.userdetails.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.util.*;
@Service
public class AccountService implements UserDetailsService {
 private final UserRepository users; private final PasswordResetTokenRepository tokens; private final VerificationTokenRepository verificationTokens; private final RoleApplicationRepository applications; private final PasswordEncoder passwords; private final JavaMailSender mail; private final SensitiveDataCrypto crypto; private final String publicUrl; private final boolean demoMode;
 public AccountService(UserRepository users, PasswordResetTokenRepository tokens, VerificationTokenRepository verificationTokens, RoleApplicationRepository applications, PasswordEncoder passwords, JavaMailSender mail, SensitiveDataCrypto crypto, @Value("${app.public-url:http://localhost:8080}") String publicUrl,@Value("${app.demo-mode:true}") boolean demoMode){this.users=users;this.tokens=tokens;this.verificationTokens=verificationTokens;this.applications=applications;this.passwords=passwords;this.mail=mail;this.crypto=crypto;this.publicUrl=publicUrl;this.demoMode=demoMode;}
 @Override @Transactional(readOnly=true) public UserDetails loadUserByUsername(String email) { AppUser u=users.findByEmailIgnoreCase(email).orElseThrow(()->new UsernameNotFoundException("Invalid credentials")); return User.withUsername(u.getEmail()).password(u.getPasswordHash()).authorities(u.getRoles().stream().map(r->new SimpleGrantedAuthority("ROLE_"+r.name())).toList()).disabled(!u.isEnabled()).build(); }
 @Transactional public RegistrationResult register(RegistrationRequest request) { String email=request.email().trim().toLowerCase(Locale.ROOT); if(users.findByEmailIgnoreCase(email).isPresent()) throw new IllegalArgumentException("An account already exists for this email"); if(users.findByPhoneHash(hash(request.phone())).isPresent()) throw new IllegalArgumentException("An account already exists for this phone number"); validPassword(request.password()); Set<Role> requested=EnumSet.copyOf(request.roles()); if(requested.contains(Role.ADMIN)) throw new IllegalArgumentException("Administrator accounts must be provisioned by an existing administrator"); Set<Role> publicRoles=EnumSet.copyOf(requested); publicRoles.retainAll(EnumSet.of(Role.CITIZEN,Role.DONOR)); Set<Role> professional=EnumSet.copyOf(requested); professional.removeAll(EnumSet.of(Role.CITIZEN,Role.DONOR)); if(professional.size()>1) throw new IllegalArgumentException("Choose one professional role per account application"); if(publicRoles.isEmpty()) publicRoles=EnumSet.of(Role.CITIZEN); AppUser user=users.save(new AppUser(email,request.fullName().trim(),passwords.encode(request.password()),publicRoles,crypto.encrypt(request.phone()),hash(request.phone()))); UUID applicationId=null; if(!professional.isEmpty()){if(request.organisationName()==null||request.organisationName().isBlank()||request.professionalIdMasked()==null||request.professionalIdMasked().isBlank()||request.detailsJson()==null||request.detailsJson().isBlank())throw new IllegalArgumentException("Organisation, masked professional ID, and service details are required for professional roles"); Role role=professional.iterator().next(); String safeJson=request.detailsJson().trim(); if(!safeJson.startsWith("{")){try{safeJson=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(safeJson);}catch(Exception ex){safeJson="\"details\"";}} applicationId=applications.save(new RoleApplication(user,role,request.organisationName().trim(),request.professionalIdMasked().trim(),safeJson)).getId();} String emailCode=otp(),phoneCode=otp(); verificationTokens.save(new VerificationToken(user,"EMAIL","REGISTRATION",hash(emailCode))); verificationTokens.save(new VerificationToken(user,"PHONE","REGISTRATION",hash(phoneCode))); sendVerificationEmail(email,emailCode); return new RegistrationResult(emailCode,phoneCode,applicationId); }
 @Transactional public void verify(String email,String code,String channel){String hashed=hash(code);VerificationToken t=verificationTokens.findByTokenHash(hashed).stream().filter(x->x.valid(hashed)&&x.user().getEmail().equalsIgnoreCase(email)&&channel.equals(x.channel())).findFirst().orElseThrow(()->new IllegalArgumentException("Invalid or expired verification code")); if("EMAIL".equals(channel))t.user().verifyEmail();else t.user().verifyPhone();t.consume();}
 @Transactional public void requestReset(ResetRequest request) { users.findByEmailIgnoreCase(request.email().trim()).ifPresent(user -> { String raw=token(); tokens.save(new PasswordResetToken(user,hash(raw))); sendResetEmail(user.getEmail(),raw); }); }
 @Transactional public void resetPassword(ResetPasswordRequest request) { validPassword(request.newPassword()); PasswordResetToken token=tokens.findByTokenHash(hash(request.token())).orElseThrow(()->new IllegalArgumentException("This reset link is invalid or has expired")); if(!token.valid()) throw new IllegalArgumentException("This reset link is invalid or has expired"); token.getUser().changePassword(passwords.encode(request.newPassword())); token.use(); }
 @Transactional public void changePassword(String email,String currentPassword,String newPassword) { AppUser user=users.findByEmailIgnoreCase(email).orElseThrow(); if(!passwords.matches(currentPassword,user.getPasswordHash()))throw new IllegalArgumentException("Current password is incorrect"); validPassword(newPassword); user.changePassword(passwords.encode(newPassword)); }
 private void sendResetEmail(String email,String token) { MimeMessage msg=mail.createMimeMessage(); try { msg.setRecipients(MimeMessage.RecipientType.TO,email); msg.setSubject("Reset your SafeLink password"); msg.setText("Use this one-time link within 20 minutes: "+publicUrl+"/reset-password.html?token="+token); mail.send(msg); } catch(Exception ex) { throw new IllegalStateException("Password reset email could not be sent. Please try again later."); } }
 private void sendVerificationEmail(String email,String code) { MimeMessage msg=mail.createMimeMessage(); try { msg.setRecipients(MimeMessage.RecipientType.TO,email); msg.setSubject("Verify your SafeLink account"); msg.setText("Your SafeLink email verification code is: "+code+". It expires in 10 minutes."); mail.send(msg); } catch(Exception ex) { if(!demoMode) throw new IllegalStateException("Verification email could not be sent. Configure Gmail SMTP and try again."); } }
 private void validPassword(String p){ if(p==null||p.length()<8) throw new IllegalArgumentException("Password must be at least 8 characters"); }
 private String token(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String otp(){return String.format("%06d",new SecureRandom().nextInt(1_000_000));} private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
