package com.smartresponse.service;
import com.smartresponse.api.*; import com.smartresponse.domain.*; import com.smartresponse.repository.*; import org.springframework.mail.SimpleMailMessage; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class TrustedContactService {
 private final TrustedContactRepository contacts; private final UserRepository users; private final SensitiveDataCrypto crypto; private final JavaMailSender mail; public TrustedContactService(TrustedContactRepository contacts,UserRepository users,SensitiveDataCrypto crypto,JavaMailSender mail){this.contacts=contacts;this.users=users;this.crypto=crypto;this.mail=mail;}
 @Transactional public TrustedContactResponse add(String email,TrustedContactRequest r){AppUser u=users.findByEmailIgnoreCase(email).orElseThrow();TrustedContact c=contacts.save(new TrustedContact(u,r.contactName(),crypto.encrypt(r.phone()),crypto.encrypt(r.email().trim()),r.relationshipName()));return map(c);}
 @Transactional(readOnly=true) public List<TrustedContactResponse> list(String email){UUID id=users.findByEmailIgnoreCase(email).orElseThrow().getId();return contacts.findByOwnerIdAndActiveTrue(id).stream().map(this::map).toList();}
 @Transactional public void remove(String email,UUID contactId){UUID user=users.findByEmailIgnoreCase(email).orElseThrow().getId();contacts.findByIdAndOwnerId(contactId,user).orElseThrow().deactivate();}
 @Transactional(readOnly=true) public void notifyEmergency(UUID ownerId, Emergency emergency){notify(ownerId,emergency.getType()+" emergency alert",emergency.getDescription(),emergency);}
 @Transactional(readOnly=true) public void notifyRequest(UUID ownerId,String requestType,String details){notify(ownerId,requestType,details,null);}
 private void notify(UUID ownerId,String type,String details,Emergency emergency){AppUser owner=users.findById(ownerId).orElse(null);if(owner==null)return;for(TrustedContact contact:contacts.findByOwnerIdAndActiveTrue(ownerId)){try{String recipient=crypto.decrypt(contact.getEmailEncrypted());if(recipient==null||recipient.isBlank())continue;SimpleMailMessage message=new SimpleMailMessage();message.setTo(recipient);message.setSubject("SafeLink alert: "+owner.getFullName()+" needs help");String location=emergency==null?"":"\n\nLocation coordinates: "+emergency.getLatitude()+", "+emergency.getLongitude()+"\nOpen map: https://www.google.com/maps/search/?api=1&query="+emergency.getLatitude()+","+emergency.getLongitude();message.setText(owner.getFullName()+" sent a "+type+".\n\nDetails: "+(details==null?"Not provided":details)+location+"\n\nThey selected you as a trusted contact. Please try to contact them or call emergency services if necessary.");mail.send(message);}catch(Exception ignored){/* Mail delivery must not block emergency routing. */}}}
 private TrustedContactResponse map(TrustedContact c){return new TrustedContactResponse(c.getId(),c.getContactName(),c.getRelationshipName(),c.isActive());}
}
